nodefest/nodefest.github.com

2015/index.html
=> Fix about content

app/scripts/text.js
=> 基調講演のタイトルが決まった！

app/elements/component/nf-site-header/nf-site-header.html, app/index.html
=> connpassへのリンクを開放

app/index.html
@yosuke-furukawa 
aki.ort指摘の件です。今更ですが ( ˙▿˙ ; )
=> 参加費を調整中から1,000円に

app/scripts/text.js
=> がねこさんは欠席となりました

app/scripts/text.js
=> Katさんのセッションタイトルを更新

app/index.html
一回余計にカウントアップされていたのを修正しましたー
(初回 2011 で年一回なので)
=> Fix to the correct number of times

app/scripts/text.js
=> セッションタイトルの更新

app/scripts/text.js
azu さんの talk のタイトル変えましたよー
http://twitter.com/azu_re/status/657816850651328512
=> Change the title of the azu's talk

2016/index.html
=> fix typo on 2016/index.html

2016/manifest.json
so that users can add the site to their homescreen.
=> Fix 2016/manifest.json

2016/index.html
=> スポンサーバナーのaltを申請シートで申告された名前にする

2016/index.html, 2016/schedule.html, 2016/src/html/_partial/timetable-workshop.ejs
Eventually, we have a new awesome speaker at the first day🎉
Great thanks to yoshiko 😺
=> Add new speaker

2017/src/html/_partial/tickets.ejs
A small English fix on the NodeFest 2017 website.
=> NodeFest 2017: English language fix

2017/schedule.html, 2017/src/html/_partial/timetable-conference.ejs, 2017/src/html/_partial/timetable-interactive.ejs
ひろっぴーのいる司会ゾーンのB会場に日本人を集約。
また、A会場には人が集まりそうな気配のあるものを集約。
C会場が一番玄人向けでコアっぽい感じになったが、個人的には一番行きたい感じ。
=> fix(timetable): B会場に日本人を集約

2017/schedule.html, 2017/src/html/_partial/timetable-conference.ejs
=> fix a speaker name

2017/schedule.html, 2017/src/html/_partial/timetable-conference.ejs, 2017/src/html/_partial/timetable-interactive.ejs
- Node Panel Talk をやめた
- Code And Learn にした
- Data Visualization Workshop を追加した
- 休憩時間を明記した
- もろもろやったら1時間2日目の終了時間が1時間延びた(Code And Learn が 1時間では終わらないため)・・・
=> fix(timetable): Add visualization workshop by sherly wu

2017/schedule.html
- Added `sugai` to performers list.
- サスカッチ told me to add him on DM
- Fixed comma
=> Update party info

2017/src/html/_partial/timetable-interactive.ejs
I guess this was a typo. cf. https://twitter.com/sxywu
=> Fix typo of a name

2018/index.html, 2018/src/html/index.ejs
We have all presentations and sponsors, we should remove the call for papers and call for sponsors.
=> Removing CFP and CFS

2018/src/html/_partial/navigation.ejs, 2018/src/html/_partial/speaker-overlay.ejs, 2018/src/html/index.ejs, 2018/src/html/speakers.ejs, 2018/src/html/sponsors.ejs, 2018/src/html/venues.ejs, 2018/src/js/main.js, 2018/src/js/page/index.js, 2018/src/scss/main.scss
と、
- IndexでSponsorsの表示が消えてたのをなおす
- IndexでFeaturedなSpeakersをしぼる
対応。
Scheduleは別で作業中だと思うのでノータッチ。
=> Speaker, Sponsor, Venueの個別ページ

2018/speakers.html, 2018/src/html/speakers.ejs
The speaker sorting on this homepage feels random.
This PR adds sorting to the speaker list based on the schedule:
_sort order_
1. Featured speakers on top
2. Lightning-talk speakers on bottom
3. Earlier speakers first
4. Lower room number first
=> Structured Speaker sorting

2018/src/confcal/conference.confcal
Quick spelling fix reported by ohbarye
=> Fixed typo in ohbarye's presentation title

2018/schedule.html, 2018/speakers.html, 2018/src/confcal/conference.confcal
Ohba's presentation description only showed who the presentation was addressing and not the actual presentation description
=> Updated ohbarye's presentation message

2018/coc.html, 2018/src/html/coc.ejs
#165 Added navigation to Code of Conduct page and removed extra header.
=> Patch/add CoC navigation

2018/speakers.html
Add speaker name.
Before his name was accidentally removed.
https://github.com/nodefest/nodefest.github.com/commit/e16b4479a19107f849b9fbdb598c144eb9fea304
=> add: speaker name.
